package com.example.QuizGeography;

public class Country_Questions {

    public  String mQuestions[]= {
            "Afganistan",
            "Almanya",
            "A.B.D",
            "Andorra",
            "Angola",
            "Antigua ve Barbuda",
            "Arjantin",
            "Arnavutluk",
            "Avustralya",
            "Avusturya",

            "Azerbaycan",
            "Bahamalar",
            "Bahreyn",
            "Bangladeş",
            "Barbados",
            "Batı Sahra",
            "Belçika",
            "Belize",
            "Benin",
            "Beyaz Rusya",

            "Bhutan",
            "Birleşik Arap Emirlikleri",
            "Birleşik Krallık",
            "Bolivya",
            "Bosna-Hersek",
            "Botsvana",
            "Brezilya",
            "Brunei",
            "Bulgaristan",
            "Burkina Faso",

            "Burundi",
            "Cezayir",
            "Cibuti",
            "Cook Adaları",
            "Çad",
            "Çek Cumhuriyeti",
            "Çin Cumhuriyeti",
            "Çin Halk Cumhuriyeti",
            "Danimarka",
            "Demokratik Kongo Cumhuriyeti",

            "Doğu Timor",
            "Dominik Cumhuriyeti",
            "Dominika",
            "Ekvador",
            "Ekvator Ginesi",
            "El Salvador",
            "Endonezya",
            "Eritre",
            "Ermenistan",
            "Estonya",

            "Etiyopya",
            "Fas",
            "Fiji",
            "Fildişi Sahili",
            "Filipinler",
            "Finlandiya",
            "Fransa",
            "Gabon",
            "Gambiya",
            "Gana",

            "Gürcistan",
            "Gine",
            "Gine-Bissau",
            "Grenada",
            "Guatemala",
            "Guyana",
            "Güney Afrika Cumhuriyeti",
            "Güney Kore",
            "Güney Sudan",
            "Haiti",

            "Hırvatistan",
            "Hindistan",
            "Hollanda",
            "Honduras",
            "Irak",
            "İran",
            "İrlanda",
            "İspanya",
            "İsrail",
            "İsveç",

            "İsviçre",
            "İtalya",
            "İzlanda",
            "Jamaika",
            "Japonya",
            "Kamboçya",
            "Kamerun",
            "Kanada",
            "Karadağ",
            "Katar",

            "Kazakistan",
            "Kenya",
            "Kıbrıs Cumhuriyeti",
            "Kırgızistan",
            "Kiribati",
            "Kolombiya",
            "Komorlar",
            "Kongo Cumhuriyeti",
            "Kosova",
            "Kosta Rika",

            "Kuveyt",
            "Kuzey Kore",
            "Küba",
            "Laos",
            "Lesotho",
            "Letonya",
            "Liberya",
            "Libya",
            "Lihtenştayn",
            "Litvanya",

            "Lübnan",
            "Lüksemburg",
            "Macaristan",
            "Madagaskar",
            "Makedonya",
            "Malavi",
            "Maldivler",
            "Malezya",
            "Mali",
            "Malta",

            "Marshall Adaları",
            "Mauritius",
            "Meksika",
            "Mısır",
            "Mikronezya",
            "Moğolistan",
            "Moldova",
            "Monako",
            "Moritanya",
            "Mozambik",

            "Myanmar",
            "Namibya",
            "Nauru",
            "Nepal",
            "Nijer",
            "Nijerya",
            "Nikaragua",
            "Niue",
            "Norveç",
            "Orta Afrika Cumhuriyeti",

            "Özbekistan",
            "Pakistan",
            "Palau",
            "Panama",
            "Papua Yeni Gine",
            "Paraguay",
            "Peru",
            "Polonya",
            "Portekiz",
            "Romanya",

            "Ruanda",
            "Rusya",
            "Saint Kitts ve Nevis",
            "Saint Lucia",
            "Saint Vincent ve Grenadinler",
            "Samoa",
            "San Marino",
            "São Tomé ve Príncipe",
            "Senegal",
            "Seyşeller",

            "Sırbistan",
            "Sierra Leone",
            "Singapur",
            "Slovakya",
            "Slovenya",
            "Solomon Adaları",
            "Somali",
            "Sri Lanka",
            "Sudan",
            "Surinam",

            "Suriye",
            "Suudi Arabistan",
            "Svaziland",
            "Şili",
            "Tacikistan",
            "Tanzanya",
            "Tayland",
            "Togo",
            "Tonga",
            "Trinidad ve Tobago",

            "Tunus",
            "Tuvalu",
            "Türkiye",
            "Türkmenistan",
            "Uganda",
            "Ukrayna",
            "Umman",
            "Uruguay",
            "Ürdün",
            "Vanuatu",

            "Vatikan",
            "Venezuela",
            "Vietnam",
            "Yemen",
            "Yeni Zelanda",
            "Yeşil Burun Adaları",
            "Yunanistan",
            "Zambiya",
            "Zimbabve"

    };

    private  String mChoices[][]= {
            {"Atina","N.America","Kabil","Singapur"},
            {"Africa","Berlin","Ankara","Buenos Aires"},
            {"Singapur","Moskova","Kiev","Washington D.C."},
            {"Andorra le Vella","Oslo","Moskova","Hartum"},
            {"Bükreş","Washington D.C.","Ankara","Luanda"},
            {"Tunus","St John","Atina","Berlin"},
            {"Moskova","Hartum","Buenos Aires","Antarctica"},
            {"Tiran","Pekin","Duşanbe","Moskova"},
            {"Moskova","Canberra","Ankara","Atina"},
            {"Oslo","Ankara","Viyana","Dakar"},

            {"Bakü","Kiev","Oslo","Tunus"},
            {"Buenos Aires","Dakar","Amsterdam","Nassau"},
            {"Hartum","Santiago","Manama","Bükreş"},
            {"Dhaka","Duşanbe","Buenos Aires","Madrid"},
            {"Bükreş","Washington D.C.","Bridgetown","Luanda"},
            {"Laayoune","St John","Atina","Berlin"},
            {"Moskova","Hartum","Buenos Aires","Brüksel"},
            {"Tiran","Pekin","Belmopan","Moskova"},
            {"Porto-Novo","Canberra","Ankara","Atina"},
            {"Oslo","Minsk","Viyana","Dakar"},

            {"Thimphu","Kiev","Oslo","Tunus"}, // 3 - 1
            {"Buenos Aires","Abu Dabi","Amsterdam","Nassau"},
            {"Hartum","Santiago","Manama","Londra"},
            {"Dhaka","Sucre","Buenos Aires","Madrid"},
            {"Londra","Washington D.C.","Abu Dabi","Saraybosna"},
            {"Gaborone","St John","Atina","Berlin"},
            {"Moskova","Thimphu","Buenos Aires","Brasillia"},
            {"Tiran","Pekin","Bandar Seri Begawan","Moskova"},
            {"Sofya","Abu Dabi","Ankara","Atina"},
            {"Oslo","Ankara","Viyana","Ouagadougou"},

            {"Bujumbura","Kiev","Oslo","Dili"},  // 4 - 1
            {"Buenos Aires","Cezayir","Amsterdam","Abu Dabi"},
            {"Hartum","Santiago","Manama","Cibuti"},
            {"Avarua","Duşanbe","Buenos Aires","Madrid"},
            {"Thimphu","Washington D.C.","N’Djamena","Luanda"},
            {"Abu Dabi","Prag","Atina","Berlin"},
            {"Moskova","Taipei","Buenos Aires","Abu Dabi"},
            {"Tiran","Pekin","Duşanbe","Londra"},
            {"Brasillia","Canberra","Kopenhag","Atina"},
            {"Oslo","Ankara","Viyana","Kinshasa"},

            {"Bakü","Kiev","Oslo","Dili"}, // 5 -1
            {"Buenos Aires","Santo Domingo","Thimphu","Nassau"},
            {"Hartum","Santiago","Roseau","Bükreş"},
            {"Quito","Duşanbe","Buenos Aires","Madrid"},
            {"Abu Dabi","Washington D.C.","Malabo","Luanda"},
            {"Tunus","St John","Londra","San Salvador"},
            {"Thimphu","Hartum","Buenos Aires","Jakarta"},
            {"Tiran","Dili","Asmara","Moskova"},
            {"Moskova","Canberra","Erivan","Atina"},
            {"Oslo","Dili","Viyana","Tallinn"},

            {"Bakü","Addis Ababa","Oslo","Tunus"},// 6 - 1
            {"Buenos Aires","Dakar","Rabat","Nassau"},
            {"Hartum","Santiago","Suva","Bükreş"},
            {"Dhaka","Yamoussoukro","Buenos Aires","Kinshasa"},
            {"Bükreş","Washington D.C.","Manila","Suva"},
            {"Helsinki","St John","Addis Ababa","Berlin"},
            {"Moskova","Paris","Buenos Aires","Suva"},
            {"Libreville","Pekin","Rabat","Moskova"},
            {"Yamoussoukro","Addis Ababa","Banjul","Atina"},
            {"Addis Ababa","Accra","Viyana","Thimphu"},

            {"Rabat","Tiflis","Oslo","Tunus"},  // 7 - 1
            {"Buenos Aires","Dakar","Rabat","Conakry"},
            {"Bissau","Santiago","Tiflis","Bükreş"},
            {"Dhaka","Conakry","Buenos Aires","St George’s"},
            {"Guatemala City","Washington D.C.","Ankara","Luanda"},
            {"Tunus","St John","Georgetown","Berlin"},
            {"Conakry","Pretoria","Buenos Aires","Addis Ababa"},
            {"Seul","Brasillia","Bissau","Moskova"},
            {"St George’s","Cuba","Addis Ababa","Atina"},
            {"Conakry","Port-au -Prince","Tiflis","Dakar"},

            {"Zagreb","Conakry","Bissau","Tunus"},  // // 8 - 1
            {"Yeni Delhi","Tiflis","Amsterdam","Nassau"},
            {"Conakry","Santiago","Amsterdam","Bükreş"},
            {"Dhaka","Duşanbe","Buenos Aires","Tegucigalpa"},
            {"St George’s","Tiflis","Ankara","Bağdat"},
            {"Tunus","St John","Abu Dabi","Tahran"},
            {"St George’s","Hartum","Buenos Aires","Dublin"},
            {"Abu Dabi","Madrid","Duşanbe","Moskova"},
            {"Tel Aviv","Canberra","Ankara","Atina"},
            {"Oslo","Ouagadougou","Stockholm","St George’s"},

            {"Kinshasa","Kiev","Bern","Tunus"}, // 9 - 1
            {"Ouagadougou Aires","Roma","Amsterdam","Nassau"},
            {"Hartum","Santiago","Manama","Reykjavik"},
            {"Kingston","Duşanbe","Buenos Aires","Madrid"},
            {"Ouagadougou","Washington D.C.","Tokyo","Conakry"},
            {"Addis Ababa","St John","Phnom Penh","Roma"},
            {"Brasillia","Hartum","Buenos Aires","Yaoundé"},
            {"Tiran","Ottawa","Abu Dabi","Moskova"},
            {"Addis Ababa","Podgorica","Yeni Delhi","Atina"},
            {"Roma","Ankara","Doha","Abu Dabi"},

            {"Astana","Bern","Addis Ababa","Zagreb"}, // 10 - 1
            {"Buenos Aires","Nairobi","Erivan","Nassau"},
            {"Tegucigalpa","Yeni Delhi","Nicosia","Bükreş"},
            {"Bişkek","Duşanbe","Astana","Madrid"},
            {"Brasillia","Washington D.C.","Bairiki","Reykjavik"},
            {"Bern","St John","Roma","Bogota"},
            {"Moskova","Moroni","Buenos Aires","Antarctica"},
            {"Kingston","Pekin","Brazzaville","Yaoundé"},
            {"Priştine","Canberra","Ankara","Atina"},
            {"San José","Ankara","Abu Dabi","Dakar"},

            {"Kuveyt","N.America","Kabil","Singapur"},
            {"Africa","Pyongyang ","Ankara","Buenos Aires"},
            {"Singapur","Havana","Kiev","Washington D.C."},
            {"Andorra le Vella","Vientiane","Moskova","Hartum"},
            {"Bükreş","Washington D.C.","Maseru","Luanda"},
            {"Riga","St John","Atina","Berlin"},
            {"Moskova","Hartum","Monrovia","Antarctica"},
            {"Tiran","Pekin","Duşanbe","Tripoli"},
            {"Vaduz","Canberra","Ankara","Atina"},
            {"Oslo","Vilnius","Viyana","Dakar"},

            {"Bakü","Kiev","Oslo","Beyrut"},
            {"Buenos Aires","Lüksemburg","Amsterdam","Nassau"},
            {"Hartum","Santiago","Budapeşte","Bükreş"},
            {"Antananarivo","Duşanbe","Buenos Aires","Madrid"},
            {"Bükreş","Üsküp","Bridgetown","Luanda"},
            {"Laayoune","St John","Lilongwe","Berlin"},
            {"Moskova","Hartum","Buenos Aires","Male"},
            {"Kuala Lumpur","Pekin","Belmopan","Moskova"},
            {"Porto- Novo","Bamako","Ankara","Atina"},
            {"Oslo","Minsk","Viyana","Valletta"},

            {"Thimphu","Kiev","Oslo","Majuro"}, // 3 - 1
            {"Port Louis","Abu Dabi","Amsterdam","Nassau"},
            {"Hartum","Santiago","Meksiko","Londra"},
            {"Dhaka","Sucre","Buenos Aires","Kahire"},
            {"Londra","Washington D.C.","Abu Dabi","Palikir"},
            {"Ulan Batur","St John","Atina","Berlin"},
            {"Moskova","Chisinau","Buenos Aires","Brasillia"},
            {"Tiran","Pekin","Bandar Seri Begawan","Monako"},
            {"Nouakchott","Abu Dabi","Ankara","Atina"},
            {"Oslo","Maputo","Viyana","Ouagadougou"},

            {"Bujumbura","Naypyidaw","Oslo","Dili"},  // 4 - 1
            {"Buenos Aires","Cezayir","Windhoek","Abu Dabi"},
            {"Hartum","Yaren","Manama","Cibuti"},
            {"Yaren","Katmandu","Buenos Aires","Madrid"},
            {"Thimphu","Niamey","N’Djamena","Luanda"},
            {"Abu Dabi","Prag","Niamey","Abuja"},
            {"Abuja","Taipei","Managua","Abu Dabi"},
            {"Alofi","Pekin","Duşanbe","Managua"},
            {"Brasillia","Alofi","Oslo","Atina"},
            {"Oslo","Bangui","Viyana","Kinshasa"},

            {"Bakü","Kiev","Taşkent","Dili"}, // 5 -1
            {"Buenos Aires","İslamabad","Thimphu","Nassau"},
            {"Hartum","Santiago","Roseau","Ngerulmud"},
            {"Quito","Panama City","Buenos Aires","Madrid"},
            {"Port Moresby","Washington D.C.","Malabo","Luanda"},
            {"Tunus","St John","Asunción","San Salvador"},
            {"Thimphu","Hartum","Buenos Aires","Lima"},
            {"Tiran","Dili","Asmara","Varşova"},
            {"Lizbon","Canberra","Erivan","Atina"},
            {"Oslo","Dili","Bükreş","Tallinn"},

            {"Bakü","Addis Ababa","Kigali","Tunus"},// 6 - 1
            {"Moskova","Dakar","Rabat","Nassau"},
            {"Hartum","Santiago","Suva","Basseterre"},
            {"Castries","Yamoussoukro","Buenos Aires","Kinshasa"},
            {"Bükreş","Washington D.C.","Kingstown","Suva"},
            {"Helsinki","St John","Addis Ababa","Apia"},
            {"Moskova","San Marino","Buenos Aires","Suva"},
            {"Libreville","Sao Tome","Rabat","Moskova"},
            {"Yamoussoukro","Addis Ababa","Dakar","Atina"},
            {"Addis Ababa","Accra","Viyana","Victoria"},

            {"Rabat","Tiflis","Oslo","Belgrat"},  // 7 - 1
            {"Buenos Aires","Freetown","Rabat","Conakry"},
            {"Bissau","Santiago","Singapur","Bükreş"},
            {"Dhaka","Bratislava","Buenos Aires","St George’s"},
            {"Guatemala City","Washington D.C.","Ljubljana","Luanda"},
            {"Tunus","St John","Georgetown","Honiara"},
            {"Mogadişu","Pretoria","Buenos Aires","Addis Ababa"},
            {"Colombo","Brasillia","Bissau","Moskova"},
            {"St George’s","Cuba","Hartum","Atina"},
            {"Conakry","Port-au -Prince","Tiflis","Paramaribo"},

            {"Zagreb","Conakry","Şam","Tunus"},  // // 8 - 1
            {"Yeni Delhi","Tiflis","Amsterdam","Riyad"},
            {"Mbabane","Santiago","Amsterdam","Bükreş"},
            {"Dhaka","Duşanbe","Santiago","Tegucigalpa"},
            {"St George’s","Tiflis","Ankara","Duşanbe"},
            {"Tunus","Dodoma","Abu Dabi","Tahran"},
            {"St George’s","Bangkok","Buenos Aires","Dublin"},
            {"Abu Dabi","Madrid","Duşanbe","Lomé"},
            {"Tel Aviv","Canberra","Ankara","Nuku’alofa"},
            {"Oslo","Ouagadougou","Port of Spain","St George’s"},

            {"Kinshasa","Kiev","Bern","Tunus"}, // 9 - 1
            {"Ouagadougou Aires","Funafuti","Amsterdam","Nassau"},
            {"Hartum","Santiago","Ankara","Reykjavik"},
            {"Kingston","Duşanbe","Buenos Aires","Aşkabat"},
            {"Ouagadougou","Washington D.C.","Tokyo","Kampala"},
            {"Addis Ababa","Kiev","Phnom Penh","Roma"},
            {"Brasillia","Hartum","Maskat","Yaoundé"},
            {"Tiran","Ottawa","Abu Dabi","Montevideo"},
            {"Addis Ababa","Podgorica","Yeni Delhi","Amman"},
            {"Port Vila","Ankara","Doha","Abu Dabi"},

            {"Astana","Bern","Vatikan","Zagreb"}, // 10 - 1
            {"Buenos Aires","Nairobi","Karakas","Nassau"},
            {"Tegucigalpa","Yeni Delhi","Nicosia","Hanoi"},
            {"Bişkek","Duşanbe","Sanaa","Madrid"},
            {"Brasillia","Washington D.C.","Bairiki","Wellington"},
            {"Bern","St John","Roma","Praia"},
            {"Moskova","Moroni","Buenos Aires","Atina"},
            {"Kingston","Pekin","Brazzaville","Lusaka"},
            {"San José","Harare","Abu Dabi","Dakar"}

    };

    private  String mCorrectAnswer[] =
            {
                    "Kabil",
                    "Berlin",
                    "Washington D.C.",
                    "Andorra le Vella",
                    "Luanda",
                    "St John",
                    "Buenos Aires",
                    "Tiran",
                    "Canberra",
                    "Viyana",

                    "Bakü",
                    "Nassau",
                    "Manama",
                    "Dhaka",
                    "Bridgetown",
                    "Laayoune",
                    "Brüksel",
                    "Belmopan",
                    "Porto-Novo",
                    "Minsk",

                    "Thimphu",
                    "Abu Dabi",
                    "Londra",
                    "Sucre",
                    "Saraybosna",
                    "Gaborone",
                    "Brasillia",
                    "Bandar Seri Begawan",
                    "Sofya",
                    "Ouagadougou",

                    "Bujumbura",
                    "Cezayir",
                    "Cibuti",
                    "Avarua",
                    "N’Djamena",
                    "Prag",
                    "Taipei",
                    "Pekin",
                    "Kopenhag",
                    "Kinshasa",

                    "Dili",
                    "Santo Domingo",
                    "Roseau",
                    "Quito",
                    "Malabo",
                    "San Salvador",
                    "Jakarta",
                    "Asmara",
                    "Erivan",
                    "Tallinn",

                    "Addis Ababa",
                    "Rabat",
                    "Suva",
                    "Yamoussoukro",
                    "Manila",
                    "Helsinki",
                    "Paris",
                    "Libreville",
                    "Banjul",
                    "Accra",

                    "Tiflis",
                    "Conakry",
                    "Bissau",
                    "St George’s",
                    "Guatemala City",
                    "Georgetown",
                    "Pretoria",
                    "Seul",
                    "Cuba",
                    "Port-au -Prince",

                    "Zagreb",
                    "Yeni Delhi",
                    "Amsterdam",
                    "Tegucigalpa",
                    "Bağdat",
                    "Tahran",
                    "Dublin",
                    "Madrid",
                    "Tel Aviv",
                    "Stockholm",

                    "Bern",
                    "Roma",
                    "Reykjavik",
                    "Kingston",
                    "Tokyo",
                    "Phnom Penh",
                    "Yaoundé",
                    "Ottawa",
                    "Podgorica",
                    "Doha",

                    "Astana",
                    "Nairobi",
                    "Nicosia",
                    "Bişkek",
                    "Bairiki",
                    "Bogota",
                    "Moroni",
                    "Brazzaville",
                    "Priştine",
                    "San José",

                    "Kuveyt", // 11
                    "Pyongyang ",
                    "Havana",
                    "Vientiane",
                    "Maseru",
                    "Riga",
                    "Monrovia",
                    "Tripoli",
                    "Vaduz",
                    "Vilnius",

                    "Beyrut",  //12
                    "Lüksemburg",
                    "Budapeşte",
                    "Antananarivo",
                    "Üsküp",
                    "Lilongwe",
                    "Male",
                    "Kuala Lumpur",
                    "Bamako",
                    "Valletta",

                    "Majuro", //13
                    "Port Louis",
                    "Meksiko",
                    "Kahire",
                    "Palikir",
                    "Ulan Batur",
                    "Chisinau",
                    "Monako",
                    "Nouakchott",
                    "Maputo",

                    "Naypyidaw", //14
                    "Windhoek",
                    "Yaren",
                    "Katmandu",
                    "Niamey",
                    "Abuja",
                    "Managua",
                    "Alofi",
                    "Oslo",
                    "Bangui",

                    "Taşkent",  //15
                    "İslamabad",
                    "Ngerulmud",
                    "Panama City",
                    "Port Moresby",
                    "Asunción",
                    "Lima",
                    "Varşova",
                    "Lizbon",
                    "Bükreş",

                    "Kigali", //16
                    "Moskova",
                    "Basseterre",
                    "Castries",
                    "Kingstown",
                    "Apia",
                    "San Marino",
                    "Sao Tome",
                    "Dakar",
                    "Victoria",

                    "Belgrat", //17
                    "Freetown",
                    "Singapur",
                    "Bratislava",
                    "Ljubljana",
                    "Honiara",
                    "Mogadişu",
                    "Colombo",
                    "Hartum",
                    "Paramaribo",

                    "Şam", //18
                    "Riyad",
                    "Mbabane",
                    "Santiago",
                    "Duşanbe",
                    "Dodoma",
                    "Bangkok",
                    "Lomé",
                    "Nuku’alofa",
                    "Port of Spain",

                    "Tunus", //19
                    "Funafuti",
                    "Ankara",
                    "Aşkabat",
                    "Kampala",
                    "Kiev",
                    "Maskat",
                    "Montevideo",
                    "Amman",
                    "Port Vila",

                    "Vatikan", //20
                    "Karakas",
                    "Hanoi",
                    "Sanaa",
                    "Wellington",
                    "Praia",
                    "Atina",
                    "Lusaka",
                    "Harare"


            };

    public String getQuestions(int a){
        String question= mQuestions[a];
        return question;
    }

    public String getChoice1(int a){
        String choice= mChoices[a][0];
        return choice;
    }
    public String getChoice2(int a){
        String choice= mChoices[a][1];
        return choice;
    }
    public String getChoice3(int a){
        String choice= mChoices[a][2];
        return choice;
    }
    public String getChoice4(int a){
        String choice= mChoices[a][3];
        return choice;
    }

    public String getCorrectAnswer(int a){

        String answer= mCorrectAnswer[a];
        return answer;

    }
}
