package com.example.QuizGeography;

public class Country_Database {

    String[] country={

            "Afganistan",
            "Almanya",
            "A.B.D",
            "Andorra",
            "Angola",
            "Antigua ve Barbuda",
            "Arjantin",
            "Arnavutluk",
            "Avustralya",
            "Avusturya",

            "Azerbaycan",
            "Bahamalar",
            "Bahreyn",
            "Bangladeş",
            "Barbados",
            "Batı Sahra",
            "Belçika",
            "Belize",
            "Benin",
            "Beyaz Rusya",

            "Bhutan",
            "Birleşik Arap Emirlikleri",
            "Birleşik Krallık",
            "Bolivya",
            "Bosna-Hersek",
            "Botsvana",
            "Brezilya",
            "Brunei",
            "Bulgaristan",
            "Burkina Faso",

            "Burundi",
            "Cezayir",
            "Cibuti",
            "Cook Adaları",
            "Çad",
            "Çek Cumhuriyeti",
            "Çin Cumhuriyeti",
            "Çin Halk Cumhuriyeti",
            "Danimarka",
            "Demokratik Kongo Cumhuriyeti",

            "Doğu Timor",
            "Dominik Cumhuriyeti",
            "Dominika",
            "Ekvador",
            "Ekvator Ginesi",
            "El Salvador",
            "Endonezya",
            "Eritre",
            "Ermenistan",
            "Estonya",

            "Etiyopya",
            "Fas",
            "Fiji",
            "Fildişi Sahili",
            "Filipinler",
            "Finlandiya",
            "Fransa",
            "Gabon",
            "Gambiya",
            "Gana",

            "Gürcistan",
            "Gine",
            "Gine-Bissau",
            "Grenada",
            "Guatemala",
            "Guyana",
            "Güney Afrika Cumhuriyeti",
            "Güney Kore",
            "Güney Sudan",
            "Haiti",

            "Hırvatistan",
            "Hindistan",
            "Hollanda",
            "Honduras",
            "Irak",
            "İran",
            "İrlanda",
            "İspanya",
            "İsrail",
            "İsveç",

            "İsviçre",
            "İtalya",
            "İzlanda",
            "Jamaika",
            "Japonya",
            "Kamboçya",
            "Kamerun",
            "Kanada",
            "Karadağ",
            "Katar",

            "Kazakistan",
            "Kenya",
            "Kıbrıs Cumhuriyeti",
            "Kırgızistan",
            "Kiribati",
            "Kolombiya",
            "Komorlar",
            "Kongo Cumhuriyeti",
            "Kosova",
            "Kosta Rika",

            "Kuveyt",
            "Kuzey Kore",
            "Küba",
            "Laos",
            "Lesotho",
            "Letonya",
            "Liberya",
            "Libya",
            "Lihtenştayn",
            "Litvanya",

            "Lübnan",
            "Lüksemburg",
            "Macaristan",
            "Madagaskar",
            "Makedonya",
            "Malavi",
            "Maldivler",
            "Malezya",
            "Mali",
            "Malta",

            "Marshall Adaları",
            "Mauritius",
            "Meksika",
            "Mısır",
            "Mikronezya",
            "Moğolistan",
            "Moldova",
            "Monako",
            "Moritanya",
            "Mozambik",

            "Myanmar",
            "Namibya",
            "Nauru",
            "Nepal",
            "Nijer",
            "Nijerya",
            "Nikaragua",
            "Niue",
            "Norveç",
            "Orta Afrika Cumhuriyeti",

            "Özbekistan",
            "Pakistan",
            "Palau",
            "Panama",
            "Papua Yeni Gine",
            "Paraguay",
            "Peru",
            "Polonya",
            "Portekiz",
            "Romanya",

            "Ruanda",
            "Rusya",
            "Saint Kitts ve Nevis",
            "Saint Lucia",
            "Saint Vincent ve Grenadinler",
            "Samoa",
            "San Marino",
            "São Tomé ve Príncipe",
            "Senegal",
            "Seyşeller",

            "Sırbistan",
            "Sierra Leone",
            "Singapur",
            "Slovakya",
            "Slovenya",
            "Solomon Adaları",
            "Somali",
            "Sri Lanka",
            "Sudan",
            "Surinam",

            "Suriye",
            "Suudi Arabistan",
            "Svaziland",
            "Şili",
            "Tacikistan",
            "Tanzanya",
            "Tayland",
            "Togo",
            "Tonga",
            "Trinidad ve Tobago",

            "Tunus",
            "Tuvalu",
            "Türkiye",
            "Türkmenistan",
            "Uganda",
            "Ukrayna",
            "Umman",
            "Uruguay",
            "Ürdün",
            "Vanuatu",

            "Vatikan",
            "Venezuela",
            "Vietnam",
            "Yemen",
            "Yeni Zelanda",
            "Yeşil Burun Adaları",
            "Yunanistan",
            "Zambiya",
            "Zimbabve"





    };
    String[] answers={

            "Kabil",
            "Berlin",
            "Washington D.C.",
            "Andorra le Vella",
            "Luanda",
            "St John",
            "Buenos Aires",
            "Tiran",
            "Canberra",
            "Viyana",

            "Bakü",
            "Nassau",
            "Manama",
            "Dakka",
            "Bridgetown",
            "Laayoune",
            "Brüksel",
            "Belmopan",
            "Porto-Novo",
            "Minsk",

            "Thimphu",
            "Abu Dabi",
            "Londra",
            "Sucre",
            "Saraybosna",
            "Gaborone",
            "Brasillia",
            "Bandar Seri Begawan",
            "Sofya",
            "Ouagadougou",

            "Bujumbura",
            "Cezayir",
            "Cibuti",
            "Avarua",
            "N’Djamena",
            "Prag",
            "Taipei",
            "Pekin",
            "Kopenhag",
            "Kinshasa",

            "Dili",
            "Santo Domingo",
            "Roseau",
            "Quito",
            "Malabo",
            "San Salvador",
            "Jakarta",
            "Asmara",
            "Erivan",
            "Tallinn",

            "Addis Ababa",
            "Rabat",
            "Suva",
            "Yamoussoukro",
            "Manila",
            "Helsinki",
            "Paris",
            "Libreville",
            "Banjul",
            "Accra",

            "Tiflis",
            "Conakry",
            "Bissau",
            "St George’s",
            "Guatemala City",
            "Georgetown",
            "Pretoria",
            "Seul",
            "Cuba",
            "Port-au -Prince",

            "Zagreb",
            "Yeni Delhi",
            "Amsterdam",
            "Tegucigalpa",
            "Bağdat",
            "Tahran",
            "Dublin",
            "Madrid",
            "Tel Aviv",
            "Stockholm",

            "Bern",
            "Roma",
            "Reykjavik",
            "Kingston",
            "Tokyo",
            "Phnom Penh",
            "Yaoundé",
            "Ottawa",
            "Podgorica",
            "Doha",

            "Astana",
            "Nairobi",
            "Nicosia",
            "Bişkek",
            "Bairiki",
            "Bogota",
            "Moroni",
            "Brazzaville",
            "Priştine",
            "San José",

            "Kuveyt", // 11
            "Pyongyang ",
            "Havana",
            "Vientiane",
            "Maseru",
            "Riga",
            "Monrovia",
            "Tripoli",
            "Vaduz",
            "Vilnius",

            "Beyrut",  //12
            "Lüksemburg",
            "Budapeşte",
            "Antananarivo",
            "Üsküp",
            "Lilongwe",
            "Male",
            "Kuala Lumpur",
            "Bamako",
            "Valletta",

            "Majuro", //13
            "Port Louis",
            "Meksiko",
            "Kahire",
            "Palikir",
            "Ulan Batur",
            "Chisinau",
            "Monako",
            "Nouakchott",
            "Maputo",

            "Naypyidaw", //14
            "Windhoek",
            "Yaren",
            "Katmandu",
            "Niamey",
            "Abuja",
            "Managua",
            "Alofi",
            "Oslo",
            "Bangui",

            "Taşkent",  //15
            "İslamabad",
            "Ngerulmud",
            "Panama City",
            "Port Moresby",
            "Asunción",
            "Lima",
            "Varşova",
            "Lizbon",
            "Bükreş",

            "Kigali", //16
            "Moskova",
            "Basseterre",
            "Castries",
            "Kingstown",
            "Apia",
            "San Marino",
            "Sao Tome",
            "Dakar",
            "Victoria",

            "Belgrat", //17
            "Freetown",
            "Singapur",
            "Bratislava",
            "Ljubljana",
            "Honiara",
            "Mogadişu",
            "Colombo",
            "Hartum",
            "Paramaribo",

            "Şam", //18
            "Riyad",
            "Mbabane",
            "Santiago",
            "Duşanbe",
            "Dodoma",
            "Bangkok",
            "Lomé",
            "Nuku’alofa",
            "Port of Spain",

            "Tunus", //19
            "Funafuti",
            "Ankara",
            "Aşkabat",
            "Kampala",
            "Kiev",
            "Maskat",
            "Montevideo",
            "Amman",
            "Port Vila",

            "Vatikan", //20
            "Karakas",
            "Hanoi",
            "Sanaa",
            "Wellington",
            "Praia",
            "Atina",
            "Lusaka",
            "Harare"


    };
}




