package com.example.QuizGeography;

public class Flag_Database {

    Integer[] flags={
            R.drawable.abd,
            R.drawable.afganistan,
            R.drawable.almanya,
            R.drawable.andorra,
            R.drawable.angola,
            R.drawable.antiguaandbarbuda,
            R.drawable.arjantin,
            R.drawable.arnavutluk,
            R.drawable.avusturalya,
            R.drawable.avusturya,

            R.drawable.azerbaycan,
            R.drawable.bahama,
            R.drawable.bahreyn,
            R.drawable.banglades,
            R.drawable.barbados,
            R.drawable.batisahra,
            R.drawable.belarus,
            R.drawable.belcika,
            R.drawable.belize,
            R.drawable.benin,

            R.drawable.bhutan,
            R.drawable.birlesikarap,
            R.drawable.bolivya,
            R.drawable.bosna,
            R.drawable.botsvana,
            R.drawable.brezilya,
            R.drawable.brunei,
            R.drawable.bulgaristan,
            R.drawable.burkinafaso,
            R.drawable.burundi,

            R.drawable.cek,
            R.drawable.cezayir,
            R.drawable.cibuti,
            R.drawable.cinhalk,
            R.drawable.danimarka,
            R.drawable.demokratikkongo,
            R.drawable.dogutimor,
            R.drawable.dominica,
            R.drawable.dominikcum,
            R.drawable.ekvador,

            R.drawable.endonezya,
            R.drawable.eritre,
            R.drawable.ermenistan,
            R.drawable.estonya,
            R.drawable.etiyopya,
            R.drawable.fiji,
            R.drawable.fildisi,
            R.drawable.filipinler,
            R.drawable.finlandiya,
            R.drawable.fransa,

            R.drawable.gabon,
            R.drawable.gambiya,
            R.drawable.gana,
            R.drawable.gine,
            R.drawable.ginebissau,
            R.drawable.greneda,
            R.drawable.guatemala,
            R.drawable.guneyafrika,
            R.drawable.guneykore,
            R.drawable.gurcistan,

            R.drawable.guyana,
            R.drawable.haiti,
            R.drawable.hindistan,
            R.drawable.hirvatistan,
            R.drawable.hollanda,
            R.drawable.honduras,
            R.drawable.ingiltere,
            R.drawable.irak,
            R.drawable.iran,
            R.drawable.irlanda,

            R.drawable.ispanya,
            R.drawable.israil,
            R.drawable.isvec,
            R.drawable.isvicre,
            R.drawable.italya,
            R.drawable.izlanda,
            R.drawable.jamaika,
            R.drawable.japonya,
            R.drawable.kambocya,
            R.drawable.kamerun,

            R.drawable.kanada,
            R.drawable.karadag,
            R.drawable.katar,
            R.drawable.kazakistan,
            R.drawable.kenya,
            R.drawable.kibris,
            R.drawable.kirgizistan,
            R.drawable.kiribati,
            R.drawable.kolombiya,
            R.drawable.komorlar,

            R.drawable.kongodemokratik,
            R.drawable.kosova,
            R.drawable.kostarika,
            R.drawable.kuba,
            R.drawable.kuveyt,
            R.drawable.kuzeykore,
            R.drawable.laos,
            R.drawable.lesotho,
            R.drawable.letonya,
            R.drawable.liberya,

            R.drawable.libya,
            R.drawable.liechtenstein,
            R.drawable.litvanya,
            R.drawable.lubnan,
            R.drawable.lucia,
            R.drawable.luksemburg,
            R.drawable.macaristan,
            R.drawable.madagaskar,
            R.drawable.makedonya,
            R.drawable.malavi,

            R.drawable.maldivler,
            R.drawable.malezya,
            R.drawable.mali,
            R.drawable.malta,
            R.drawable.marshall,
            R.drawable.mauritius,
            R.drawable.meksika,
            R.drawable.mikronezya,
            R.drawable.misir,
            R.drawable.mogalistan,

            R.drawable.moldova,
            R.drawable.monaco,
            R.drawable.moritanya,
            R.drawable.mozambik,
            R.drawable.nabipya,
            R.drawable.nauru,
            R.drawable.nepal,
            R.drawable.nijer,
            R.drawable.nijerya,
            R.drawable.nikaragua,

            R.drawable.norvec,
            R.drawable.oman,
            R.drawable.ortaafrika,
            R.drawable.ozbekistan,
            R.drawable.pakistan,
            R.drawable.palau,
            R.drawable.panama,
            R.drawable.papuayenigine,
            R.drawable.paraguay,
            R.drawable.peru,

            R.drawable.polonya,
            R.drawable.portekiz,
            R.drawable.romanya,
            R.drawable.ruanda,
            R.drawable.rusya,
            R.drawable.saintnevis,
            R.drawable.samoa,
            R.drawable.sanmarino,
            R.drawable.saotome,
            R.drawable.senegal,

            R.drawable.seyseller,
            R.drawable.sierraleone,
            R.drawable.sili,
            R.drawable.singapur,
            R.drawable.sirbistan,
            R.drawable.slovakya,
            R.drawable.slovenya,
            R.drawable.solomon,
            R.drawable.somali,
            R.drawable.srilanka,

            R.drawable.stvincent,
            R.drawable.sudan,
            R.drawable.surinam,
            R.drawable.suriye,
            R.drawable.suudi,
            R.drawable.swaziland,
            R.drawable.tacikistan,
            R.drawable.tanzanya,
            R.drawable.tayland,
            R.drawable.tobago,

            R.drawable.togo,
            R.drawable.tonga,
            R.drawable.tunus,
            R.drawable.turkiye,
            R.drawable.turkmenistan,
            R.drawable.tuvalu,
            R.drawable.uganda,
            R.drawable.ukrayna,
            R.drawable.urdun,
            R.drawable.uruguay,

            R.drawable.vanuatu,
            R.drawable.vatikan,
            R.drawable.venezuela,
            R.drawable.vietnam,
            R.drawable.yemen,
            R.drawable.yenizelanda,
            R.drawable.yesilburun,
            R.drawable.yunanistan,
            R.drawable.zambia,
            R.drawable.zimbabwe
    };
    String[] answers={
            "abd","afganistan","almanya","andorra","angola","antigua ve barbuda","arjantin","arnavutluk","avusturalya","avusturya",
            "azerbaycan","bahama adaları","bahreyn","bangladeş","barbados","batı sahra","belarus","belçika","belize","benin",
            "bhutan","birlesik arap emirlikleri","bolivya","bosna hersek","botsvana","brezilya","brunei","bulgaristan","burkina faso","burundi",
            "çekya","cezayir","cibuti","çin halk cumhuriyeti","danimarka","demokratik kongo cum.","doğu timor","dominika","dominik cumhuriyeti","ekvador",
            "endonezya","eritre","ermenistan","estonya","etiyopya","fiji","fildişi sahilleri","filipinler","finlandiya","fransa",
            "gabon","gambiya","gana","gine","gine bissau","greneda","guatemala","güney afrika","güney kore","gürcistan",
            "guyana","haiti","hindistan","hırvatistan","hollanda","honduras","ingiltere","ırak","iran","irlanda",
            "ispanya","israil","isveç","isviçre","italya","izlanda","jamaika","japonya","kamboçya","kamerun",
            "kanada","karadağ","katar","kazakistan","kenya","kıbrıs","kırgızistan","kiribati","kolombiya","komorlar",
            "kongo demokratik cum.","kosova","kosta rika","küba","kuveyt","kuzey kore","laos","lesotho","letonya","liberya",
            "libya","liechtenstein","litvanya","lübnan","lucia","lüksemburg","macaristan","madagaskar","makedonya","malavi",
            "maldivler","malezya","mali","malta","marshall adaları","mauritius","meksika","mikronezya","mısır","moğolistan",
            "moldova","monako","moritanya","mozambik","nabipya","nauru","nepal","nijer","nijerya","nikaragua",
            "norvec","umman","orta afrika cum.","özbekistan","pakistan","palau","panama","papua yine gine","paraguay","peru",
            "polonya","portekiz","romanya","ruanda","rusya federasyonu","Saint nevis","samoa","san marino","sao tome","senegal",
            "seyşeller","sierra leone","şili","singapur","sırbistan","slovakya","slovenya","solomon adaları","somali","sri lanka",
            "St vincent","Sudan","surinam","suriye","suudi arabistan","swaziland","tacikistan","tanzanya","tayland", "tobago",
            "togo","tonga","tunus","türkiye","türkmenistan","tuvalu","uganda","ukrayna","ürdün", "uruguay",
            "vanuatu","vatikan","venezuela","vietnam","yemen","yeni zelanda","yeşil burun adaları","yunanistan","zambia","zimbabwe"
    };
}
